name: Build mysql-client image

env:
    DOCKER_USER: ${{secrets.DOCKER_USER}}
    REPO_NAME: mysql-client


on:
    push:
        branches:
        - main
        paths:
        - mysql-client

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: |
            cd mysql-client
            docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:latest
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
                username: ${{secrets.DOCKER_USER}}
                password: ${{secrets.DOCKER_TOKEN}}
        - name: Push the Docker image
          run: docker push $DOCKER_USER/$REPO_NAME:latest

